# vim:fileencoding=utf-8:foldmethod=marker

editor /opt/homebrew/bin/nvim

# Font
font_size 13
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

# Tmux
tab_bar_style powerline
tab_powerline_style angled
tab_activity_symbol ‚óè
tab_title_template "{index}: {title}"
map ctrl+b>& close_window
map ctrl+b>c new_tab
map ctrl+b>n next_tab
map ctrl+b>p previous_tab
map ctrl+b>, rename_tab
map ctrl+b>1 goto_tab 1
map ctrl+b>2 goto_tab 2
map ctrl+b>3 goto_tab 3
map ctrl+b>4 goto_tab 4
map ctrl+b>5 goto_tab 5
map ctrl+b>6 goto_tab 6
map ctrl+b>7 goto_tab 7
map ctrl+b>8 goto_tab 8
map ctrl+b>9 goto_tab 9
map ctrl+b>0 goto_tab 10
map ctrl+b>% launch --location=vsplit
map ctrl+b>" launch --location=hsplit

# Nightfox colors for Kitty
## name: nightfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/nightfox_kitty.conf

background #192330
foreground #cdcecf
selection_background #2b3b51
selection_foreground #cdcecf
url_color #81b29a

# Cursor
# uncomment for reverse background
# cursor none
cursor #cdcecf
cursor_shape beam

# Border
active_border_color #719cd6
inactive_border_color #39506d
bell_border_color #f4a261

# Tabs
active_tab_background #719cd6
active_tab_foreground #131a24
inactive_tab_background #2b3b51
inactive_tab_foreground #738091

# normal
color0 #393b44
color1 #c94f6d
color2 #81b29a
color3 #dbc074
color4 #719cd6
color5 #9d79d6
color6 #63cdcf
color7 #dfdfe0

# bright
color8 #575860
color9 #d16983
color10 #8ebaa4
color11 #e0c989
color12 #86abdc
color13 #baa1e2
color14 #7ad5d6
color15 #e4e4e5

# extended colors
color16 #f4a261
color17 #d67ad2
