format = """
$cmd_duration$character\
$directory\
$git_branch$git_status\
$fill\
$docker_context$c$dart$elixir$elm$golang$gradle$haskell$java$lua$nodejs$nim$rust$scala$php\
\n❯"""

[fill]
symbol = " "
style = "fg:#cdd6f4 bg:#11111b"

[character]
format = "$symbol"
success_symbol = ""
error_symbol = "[Error](fg:#f38ba8)\n\n" 

[cmd_duration]
format = "took [$duration]($style)\n\n"

[directory]
style = "fg:#11111b bg:#89b4fa"
format = "[ $path ]($style)"
read_only = " "
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:#cdd6f4 bg:#45475a"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#cdd6f4 bg:#45475a"
format = '[$all_status$ahead_behind ]($style)'
deleted = "-"

[c]
symbol = " "
style = "fg:#89b4fa bg:#11111b"
format = '[ $symbol ($version) ]($style)'

[dart]
symbol = " "
style = "fg:#89b4fa bg:#11111b"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#89b4fa bg:#11111b"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "fg:#cba6f7 bg:#11111b"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#89dceb bg:#11111b"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "fg:#74c7ec bg:#11111b"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:#94e2d5 bg:#11111b"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#cba6f7 bg:#11111b"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#fab387 bg:#11111b"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = " "
style = "fg:#89b4fa bg:#11111b"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#a6e3a1 bg:#11111b"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:#f9e2af bg:#11111b"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#fab387 bg:#11111b"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:#eba0ac bg:#11111b"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = " "
style = "fg:#eba0ac bg:#11111b"
format = '[ $symbol ($version) ]($style)'

