[v1]
"cargo-update 13.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"coreutils 0.0.24 (registry+https://github.com/rust-lang/crates.io-index)" = ["coreutils"]
"languagetool-rust 2.1.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["ltrs"]
"selene 0.26.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["selene"]
